### ISSUE TITLE
Unable to connect to LND from host machine

### ISSUE THREAD

**Issue by yzernik** [vulpemventures/nigiri#157]
I started nigiri with LND using this command:

```
nigiri start --ln
```

I verified that the docker container is running:

```
$ docker ps -a
CONTAINER ID   IMAGE                                             COMMAND                  CREATED        STATUS                       PORTS                                                                        NAMES
1dd8b9be2f27   elementsproject/lightningd:latest                 "/usr/bin/tini -g --…"   20 hours ago   Up 11 seconds                0.0.0.0:9835->9835/tcp, 9735/tcp, 0.0.0.0:9935->9935/tcp                     cln
76506df8dc91   lightninglabs/lnd:v0.14.3-beta                    "lnd"                    20 hours ago   Up 11 seconds                0.0.0.0:9735->9735/tcp, 0.0.0.0:10009->10009/tcp                             lnd
f40818501844   ghcr.io/vulpemventures/esplora:latest             "docker-entrypoint.s…"   10 days ago    Up 11 seconds                0.0.0.0:5000->5000/tcp                                                       esplora
568167eb04bd   ghcr.io/vulpemventures/nigiri-chopsticks:latest   "/app --use-faucet -…"   10 days ago    Up 11 seconds                0.0.0.0:3000->3000/tcp                                                       chopsticks
238c6aff0bd9   ghcr.io/vulpemventures/electrs:latest             "/build/electrs -vvv…"   10 days ago    Up 11 seconds                0.0.0.0:30000->30000/tcp, 0.0.0.0:50000->50000/tcp                           electrs
51b93ef37646   ghcr.io/vulpemventures/bitcoin:latest             "bitcoind -datadir=c…"   10 days ago    Up 12 seconds                0.0.0.0:18443-18444->18443-18444/tcp, 0.0.0.0:28332-28333->28332-28333/tcp   bitcoin
```

`nigiri lnd getinfo` command works:

```
$ nigiri lnd getinfo
{
    "version": "0.14.3-beta commit=v0.14.3-beta",
...
```

But I am not able to make an RPC connection to LND from my host machine using this simple script:
```
import lightning_pb2 as ln
import lightning_pb2_grpc as lnrpc
import grpc
import os
import codecs

os.environ["GRPC_SSL_CIPHER_SUITES"] = 'HIGH+ECDSA'

with open(os.path.expanduser('~/.nigiri/volumes/lnd/data/chain/bitcoin/regtest/admin.macaroon'), 'rb') as f:
    macaroon_bytes = f.read()
    macaroon = codecs.encode(macaroon_bytes, 'hex')

cert = open(os.path.expanduser('~/.nigiri/volumes/lnd/tls.cert'), 'rb').read()
creds = grpc.ssl_channel_credentials(cert)
channel = grpc.secure_channel('localhost:10009', creds)
stub = lnrpc.LightningStub(channel)

response = stub.GetInfo(ln.GetInfoRequest(), metadata=[('macaroon', macaroon)])
print(response)
```

Output:
```
$ python3 example.py 
Traceback (most recent call last):
  File "example.py", line 18, in <module>
    response = stub.GetInfo(ln.GetInfoRequest(), metadata=[('macaroon', macaroon)])
  File "/home/yzernik/work/tmp/lnd_py_2/venv/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/yzernik/work/tmp/lnd_py_2/venv/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1656553797.970224941","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1656553797.970223986","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>
```

**Comment by yzernik** [comment]
I see this line in the LND logs:

```
2022-06-30 03:13:08.623 [INF] RPCS: RPC server listening on 127.0.0.1:10009
```

Maybe it needs to be configured to use `[::]:10009` or `0.0.0.0:10009`?

**Comment by yzernik** [comment]
Maybe set this config for LND:

```
--rpclisten=0.0.0.0:10009
```

**Comment by tiero** [comment]
> --rpclisten=0.0.0.0:10009

Thanks for reporting this. Pretty sure that is the reason.

You can eventually try yourself

go to your $HOME/.nigiri  (or ` ~/Library/Application\ Support/Nigiri` if on OSX) and tweak he docker-compose.yml and in the `lnd` service add 

```yml
command:
    - --rpclisten=0.0.0.0:10009
```

**Comment by tiero** [comment]
Can you review this and test the binary for your OS/ARCH combo? A zip is attached in the comment @yzernik 



https://github.com/vulpemventures/nigiri/pull/158
